# Generated by Django 6.0.2 on 2026-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joblib_path', models.CharField(max_length=500, unique=True)),
                ('target_functionality', models.CharField(help_text='e.g. Toxicity, Solubility', max_length=100)),
                ('training_accuracy', models.FloatField(default=0.0)),
                ('training_f1_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='NMRTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(max_length=230)),
                ('peak_string', models.TextField(help_text='Paste your 000... string here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
