# Generated by Django 6.0.2 on 2026-02-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodelmetadata',
            name='name',
        ),
        migrations.AddField(
            model_name='mlmodelmetadata',
            name='scaler_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='joblib_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mlmodelmetadata',
            name='target_functionality',
            field=models.CharField(max_length=255),
        ),
    ]
