# Generated by Django 6.0.2 on 2026-02-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0002_remove_mlmodelmetadata_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelmetadata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
