# Generated by Django 6.0.2 on 2026-02-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0003_mlmodelmetadata_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(max_length=255)),
                ('peak_string', models.TextField()),
                ('prediction_results', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
